# -*- coding: utf-8 -*-
"""Untitled.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1QEA5t-DSH3qIJbgSjoxkwkUMn_CFj3uS

#Tina Verma
TI71


Group B: Assignments based on Data Analytics using Python
Perform the following operations using Python on the Facebook metrics data sets
a. Create data subsets

b. Merge Data

c. Sort Data

d. Transposing Data

e. Shape and reshape Data

Uploading Dataset and importing important libraries
"""

import numpy as np
import pandas as pd

df=pd.read_csv('dataset_Facebook.csv',sep=";")
df

#Describing the dataframe
df.describe()

df.shape

"""Creating Subsets"""

#Subset1
df1=df[['Page total likes','Category','Post Month','Post Weekday']].loc[0:15]
df1

#Subset2
df2=df[['Page total likes','Category','Post Month','Post Weekday']].loc[16:30]
df2

#Subset3
df3=df[['Page total likes','Category','Post Month','Post Weekday']].loc[31:50]
df3

#Merge Data
#Merging Subset1,Subset2,Subset3
merging=pd.concat([df1,df2,df3])
merging

"""Sort Data"""

sort_values=df.sort_values('Page total likes',ascending=False)
sort_values

#Transpose Data
df.transpose()

#Shaping and Reshaping data

shaping=df.shape
shaping

pivot_table=pd.pivot_table(df,index=['Type','Category'],values='like')
print(pivot_table)

reshaping_arr=np.array([1,2,3,4,5,6])
reshaping_arr.reshape(3,2)

